'use client';

import React, { useEffect, useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { Eyebrow, MagneticLink, Reveal } from './primitives';
import { useInView, useReducedMotion } from '../lib/motion';

type Tok = [cls: '' | 'k' | 's' | 'c' | 'f', text: string];

const FILES: Record<string, Tok[][]> = {
  'pipeline.py': [
    [['c', '# Generated by Nebulus — reproduces cleaned_titanic.csv']],
    [['k', 'import'], ['', ' pandas '], ['k', 'as'], ['', ' pd']],
    [],
    [['k', 'def'], ['f', ' clean_data'], ['', '(df):']],
    [['', '    df = '], ['f', 'drop_rows_missing'], ['', '(df, '], ['s', '"Survived"'], ['', ')']],
    [['', '    df = '], ['f', 'drop_duplicate_rows'], ['', '(df, subset=['], ['s', '"Pclass"'], ['', ', ...])']],
    [['', '    df = '], ['f', 'drop_columns'], ['', '(df, ['], ['s', '"PassengerId"'], ['', '])']],
    [['', '    df = '], ['f', 'replace_negatives'], ['', '(df, '], ['s', '"Age"'], ['', ', 28.0)']],
    [['', '    df = '], ['f', 'clip_values'], ['', '(df, '], ['s', '"Fare"'], ['', ', -26.72, 65.63)']],
    [['', '    df = '], ['f', 'fill_missing'], ['', '(df, '], ['s', '"Embarked"'], ['', ', '], ['s', '"S"'], ['', ')']],
    [['', '    df = '], ['f', 'one_hot'], ['', '(df, '], ['s', '"Sex"'], ['', ', ['], ['s', '"female"'], ['', ', '], ['s', '"male"'], ['', '])']],
    [['k', '    return'], ['', ' df']],
  ],
  'manifest.json': [
    [['', '{']],
    [['s', '  "dataset"'], ['', ': '], ['s', '"titanic.csv"'], ['', ',']],
    [['s', '  "health"'], ['', ': { '], ['s', '"before"'], ['', ': 54.2, '], ['s', '"after"'], ['', ': 93.8 },']],
    [['s', '  "target"'], ['', ': '], ['s', '"Survived"'], ['', ',']],
    [['s', '  "applied_steps"'], ['', ': [']],
    [['s', '    "Dropped 1 rows with missing target"'], ['', ',']],
    [['s', '    "Dropped 4 duplicate rows"'], ['', ',']],
    [['s', '    "Capped outliers in Fare"'], ['', ',']],
    [['s', '    "Imputed Age with median (28.0)"']],
    [['', '  ]']],
    [['', '}']],
  ],
  'leaderboard': [
    [['c', '# 5-fold stratified CV · macro F1 · 2000-row sample']],
    [],
    [['k', ' #  model                    f1']],
    [['', ' 1  '], ['f', 'Support Vector Machine'], ['', '   0.781']],
    [['', ' 2  '], ['f', 'Gradient Boosting     '], ['', '   0.774']],
    [['', ' 3  '], ['f', 'Random Forest         '], ['', '   0.769']],
    [['', ' 4  '], ['f', 'Logistic Regression   '], ['', '   0.762']],
    [['', ' 5  '], ['f', 'Decision Tree         '], ['', '   0.731']],
    [],
    [['c', '# no 1.000 here: preprocessing is fitted inside each fold']],
  ],
};

const totalChars = (lines: Tok[][]) => lines.reduce((n, l) => n + l.reduce((m, t) => m + t[1].length, 0) + 1, 0);

function Typed({ lines, chars }: { lines: Tok[][]; chars: number }) {
  let left = chars;
  return (
    <>
      {lines.map((line, li) => {
        if (left <= 0) return null;
        const parts = line.map(([cls, text], ti) => {
          if (left <= 0) return null;
          const shown = text.slice(0, left);
          left -= text.length;
          return <span key={ti} className={cls ? `tk-${cls}` : undefined}>{shown}</span>;
        });
        left -= 1;
        return <div key={li}>{parts}{line.length === 0 ? '\u00a0' : null}{left <= 0 && <span className="caret" style={{ background: '#e7e5e0' }} />}</div>;
      })}
    </>
  );
}

export function Exports() {
  const [tab, setTab] = useState<keyof typeof FILES>('pipeline.py');
  const [ref, inView] = useInView<HTMLDivElement>(0.3);
  const reduced = useReducedMotion();
  const [chars, setChars] = useState(0);
  const lines = FILES[tab];
  const total = totalChars(lines);

  useEffect(() => {
    if (!inView) return;
    if (reduced) {
      setChars(total);
      return;
    }
    setChars(0);
    let raf = 0;
    let last = 0;
    const tick = (t: number) => {
      if (t - last > 16) {
        last = t;
        setChars((c) => Math.min(total, c + 3 + Math.round(Math.random() * 4)));
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [inView, tab, total, reduced]);

  return (
    <section className="section" id="exports">
      <div className="guides" />
      <div className="frame">
        <div className="term-wrap">
          <div>
            <Reveal><Eyebrow label="artifacts" index="04/05" /></Reveal>
            <Reveal delay={80} as="h2" className="section-title" style={{ marginTop: '1rem' }}>
              Take the receipts with you.
            </Reveal>
            <Reveal delay={160} as="p" className="section-sub" style={{ marginTop: '1rem' }}>
              The fixes you approved become plain pandas code you can read, diff and run in your own pipeline.
            </Reveal>
            <Reveal delay={240} as="ul" className="term-list">
              <li><span className="n">01</span>The script reproduces the exported CSV exactly — tested on every demo dataset.</li>
              <li><span className="n">02</span>Fixed category lists, so new data is one-hot encoded the same way.</li>
              <li><span className="n">03</span>The PDF report shows every sub-score with signed before/after deltas.</li>
            </Reveal>
          </div>

          <div ref={ref} className={`reveal ${inView ? 'in' : ''}`}>
            <div className="terminal">
              <div className="term-tabs" role="tablist">
                {(Object.keys(FILES) as (keyof typeof FILES)[]).map((f) => (
                  <button key={f} role="tab" aria-selected={tab === f} className={`term-tab ${tab === f ? 'active' : ''}`} onClick={() => setTab(f)}>
                    {f}
                  </button>
                ))}
              </div>
              <div className="term-body"><Typed lines={lines} chars={chars} /></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export function CTA({ dashboardUrl }: { dashboardUrl: string }) {
  return (
    <section className="section" style={{ borderBottom: 'none' }}>
      <div className="guides" />
      <div className="frame">
        <Reveal className="cta-card">
          <span className="cta-blob a" />
          <span className="cta-blob b" />
          <span className="cta-blob c" />
          <span className="eyebrow">
            <span className="dollar" style={{ color: '#b9a6ff' }}>$</span> nebulus <span className="sep">·</span>
            <b>get started</b> <span className="count">[05/05]</span>
          </span>
          <h2>Your model is only as honest as its data.</h2>
          <p>Upload a CSV or start with Titanic, Telco churn or housing prices. You&apos;ll have a score in under a minute.</p>
          <div style={{ display: 'flex', gap: '0.6rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <MagneticLink href={dashboardUrl} className="btn btn-light btn-lg">
              Open the dashboard <ArrowRight size={15} className="arrow" />
            </MagneticLink>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

export function Footer() {
  const reduced = useReducedMotion();
  const onMove = (e: React.PointerEvent<HTMLDivElement>) => {
    const el = e.currentTarget;
    const r = el.getBoundingClientRect();
    el.style.setProperty('--mx', `${e.clientX - r.left}px`);
    el.style.setProperty('--my', `${e.clientY - r.top}px`);
    el.style.setProperty('--r', reduced ? '2000px' : '180px');
  };
  return (
    <footer className="footer">
      <div className="frame">
        <div className="footer-row">
          <span>Nebulus — explainable data readiness for ML.</span>
          <span className="mono" style={{ fontSize: '0.72rem' }}>© 2026 · built with pandas, scikit-learn & a lot of NaN</span>
        </div>
      </div>
      <div
        className="wordmark"
        onPointerMove={onMove}
        onPointerLeave={(e) => e.currentTarget.style.setProperty('--r', '0px')}
        aria-hidden
      >
        <span className="outline">NEBULUS</span>
        <span className="fill">NEBULUS</span>
      </div>
    </footer>
  );
}
